//----------------------
// <auto-generated>
//     Generated using the NSwag toolchain v14.6.3.0 (NJsonSchema v11.5.2.0 (Newtonsoft.Json v13.0.0.0)) (http://NSwag.org)
// </auto-generated>
//----------------------

/* eslint-disable */
// ReSharper disable InconsistentNaming



export interface CreateUsersDto {
    username?: string;
    fullname: string;
    email: string;
    password: string;
    phoneNumber: string;
    roles?: string[];
    profilePictureUrl?: string;
    bio?: string;
    address?: string;
    dateOfBirth?: Date;
    teamId?: number;
    isActive?: boolean;

    [key: string]: any;
}

export interface UpdateUsersDto {
    /** User full name */
    fullname?: string;
    /** User email address */
    email?: string;
    /** User password (will be hashed) */
    password?: string;
    /** User phone number */
    phoneNumber?: string;
    /** User roles */
    roles?: string[];
    /** Profile picture URL */
    profilePictureUrl?: string;
    /** User bio/description */
    bio?: string;
    /** User address */
    address?: string;
    /** User date of birth */
    dateOfBirth?: Date;

    [key: string]: any;
}

export interface LoginDto {
    /** Email address or username */
    email: string;
    /** User password */
    password: string;

    [key: string]: any;
}

export interface RegisterUserDto {
    /** Username for the new user */
    username: string;
    /** Full name of the user */
    fullname: string;
    /** Email address */
    email: string;
    /** Phone number */
    phoneNumber: string;
    /** Password for the account */
    password: string;
    /** Team ID (1-8): 1=HR, 2=IT, 3=Marketing, 4=Finance, 5=Sales, 6=Operations, 7=Legal, 8=Customer Support */
    teamId: number;
    /** Home address */
    address?: string;
    /** Date of birth (YYYY-MM-DD) */
    dateOfBirth?: string;
    /** Bio/description */
    bio?: string;
    /** Profile picture URL */
    profilePictureUrl?: string;

    [key: string]: any;
}

export interface ChangePasswordDto {
    /** Current password for verification */
    currentPassword: string;
    /** New password (minimum 6 characters) */
    newPassword: string;
    /** Confirm new password (must match newPassword) */
    confirmPassword: string;

    [key: string]: any;
}

export interface LeaveBalanceEntity {

    [key: string]: any;
}

export interface CreateBalanceDto {
    /** User ID (UUID) */
    userId: string;
    /** Leave Type ID */
    leaveTypeId: number;
    /** Year */
    year: number;
    /** Carryover days from previous year */
    carryover: number;
    /** Days already used */
    used: number;

    [key: string]: any;
}

export interface AdjustBalanceDto {
    /** Year for the leave balance */
    year: number;
    /** Number of days carried over from previous year */
    carryover: number;
    /** Number of leave days used */
    used: number;

    [key: string]: any;
}

export interface CreateLeaveTypeDto {

    [key: string]: any;
}

export interface UpdateLeaveTypeDto {
    /** Leave type name */
    name?: string;
    /** Maximum days allowed */
    maxDays?: number;

    [key: string]: any;
}

export interface CreateTeamDto {
    /** Team name */
    name: string;

    [key: string]: any;
}

export interface UpdateTeamDto {
    /** Team name */
    name?: string;

    [key: string]: any;
}

export interface CreateProfileDto {

    [key: string]: any;
}

export interface CreateLeaveRequestDto {
    /** Leave type name or ID */
    leaveType: string;
    /** Start date */
    startDate: Date;
    /** End date */
    endDate: Date;
    /** Reason for leave request */
    reason: string;
    /** Is this a half-day leave? */
    isHalfDay?: boolean;
    /** Manager email for approval */
    managerEmail?: string;
    /** Emergency contact number */
    emergencyContact?: string;
    /** Total days requested */
    totalDays?: number;

    [key: string]: any;
}

export interface UpdateLeaveStatusDto {
    /** The new status for the leave request */
    status: UpdateLeaveStatusDtoStatus;

    [key: string]: any;
}

export enum UpdateLeaveStatusDtoStatus {
    PENDING = "PENDING",
    APPROVED = "APPROVED",
    REJECTED = "REJECTED",
}